title: Bidmart Procurement Platform
description: Документация и описание платформы управления закупками
remote_theme: just-the-docs/just-the-docs
color_scheme: light
search_enabled: true
logo: "https://www.bidmart.by/img/logo-small.svg"
